In [1]:
import pandas as pd

In [2]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 8A66-F804

 Directory of C:\Users\Rokaya Neeraj\Full Stack Data Science\Python\Pandas

03/28/2022  01:28 PM    <DIR>          .
03/28/2022  01:28 PM    <DIR>          ..
03/28/2022  01:26 PM    <DIR>          .ipynb_checkpoints
03/28/2022  01:28 PM               588 Pandas.ipynb
               1 File(s)            588 bytes
               3 Dir(s)  18,105,241,600 bytes free

In [7]:
df = pd.read_csv(r"C:/Users/Rokaya Neeraj/Downloads/carbon_nanotubes.csv")
df.head()

,Chiral indice n,Chiral indice m,Initial atomic coordinate u,Initial atomic coordinate v,Initial atomic coordinate w,Calculated atomic coordinates u',Calculated atomic coordinates v'
0,2;1;0,679005;0,701318;0,017033;0,721039;0,730232;0,17014.0
1,2;1;0,717298;0,642129;0,231319;0,738414;0,65675;0,232369.0
2,2;1;0,489336;0,303751;0,088462;0,477676;0,263221;0,88712.0
3,2;1;0,413957;0,632996;0,040843;0,408823;0,657897;0,39796.0
4,2;1;0,334292;0,543401;0,15989;0,303349;0,558807;0,157373.0

Two data types in pandas:
    1. Dataframe - Complete table
    2. Series - one single column or one single row

In [8]:
df = pd.read_csv(r"C:/Users/Rokaya Neeraj/Downloads/carbon_nanotubes.csv", header = None) #default header
df.head()

,0,1,2,3,4,5,6
0,Chiral indice n,Chiral indice m,Initial atomic coordinate u,Initial atomic coordinate v,Initial atomic coordinate w,Calculated atomic coordinates u',Calculated atomic coordinates v'
1,2;1;0,679005;0,701318;0,017033;0,721039;0,730232;0,17014
2,2;1;0,717298;0,642129;0,231319;0,738414;0,65675;0,232369
3,2;1;0,489336;0,303751;0,088462;0,477676;0,263221;0,88712
4,2;1;0,413957;0,632996;0,040843;0,408823;0,657897;0,39796

In [13]:
df = pd.read_csv(r"C:/Users/Rokaya Neeraj/Downloads/carbon_nanotubes.csv", names = ["a","b","c","d","e","f"]) #passing header
df.head()

,a,b,c,d,e,f
Chiral indice n,Chiral indice m,Initial atomic coordinate u,Initial atomic coordinate v,Initial atomic coordinate w,Calculated atomic coordinates u',Calculated atomic coordinates v'
2;1;0,679005;0,701318;0,017033;0,721039;0,730232;0,17014
2;1;0,717298;0,642129;0,231319;0,738414;0,65675;0,232369
2;1;0,489336;0,303751;0,088462;0,477676;0,263221;0,88712
2;1;0,413957;0,632996;0,040843;0,408823;0,657897;0,39796

In [10]:
#checkin data types of columns
df.dtypes #object is just a string

a    object
b    object
c    object
d    object
e    object
f    object
dtype: object

In [11]:
df.columns #lists columns

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

In [12]:
df['a']

Chiral indice n    Chiral indice m
2;1;0                     679005;0
2;1;0                     717298;0
2;1;0                     489336;0
2;1;0                     413957;0
                        ...
12;6;0                    834201;0
12;6;0                    698374;0
12;6;0                    923823;0
12;6;0                    934978;0
12;6;0                    953664;0
Name: a, Length: 10722, dtype: object

In [14]:
x = df['a']
type(x)

pandas.core.series.Series

In [18]:
#df['a','b'] #it will give error.pass list of column
name = df[['a','b']]
name

                               a                            b
Chiral indice n  Chiral indice m  Initial atomic coordinate u
2;1;0                   679005;0                     701318;0
2;1;0                   717298;0                     642129;0
2;1;0                   489336;0                     303751;0
2;1;0                   413957;0                     632996;0
...                          ...                          ...
12;6;0                  834201;0                     399891;0
12;6;0                  698374;0                      24471;0
12;6;0                  923823;0                     568913;0
12;6;0                  934978;0                     602319;0
12;6;0                  953664;0                     698374;0

[10722 rows x 2 columns]

In [19]:
type(name)

pandas.core.frame.DataFrame

In [21]:
type(df['a']) #single column gives series

pandas.core.series.Series

In [22]:
type(df[['a']]) #double column gives dataframe

pandas.core.frame.DataFrame

In [23]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 8A66-F804

 Directory of C:\Users\Rokaya Neeraj\Full Stack Data Science\Python\Pandas

03/28/2022  02:27 PM    <DIR>          .
03/28/2022  02:27 PM    <DIR>          ..
03/28/2022  01:41 PM    <DIR>          .ipynb_checkpoints
03/28/2022  02:27 PM           161,651 LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx
03/28/2022  02:27 PM           161,410 LUSID Excel - Maintain a product in multiple currencies and share classes.xlsx
03/28/2022  02:27 PM            24,471 LUSID Excel - Manage instruments with economic definitions.xlsx
03/28/2022  02:27 PM            84,319 LUSID Excel - Manage Orders.xlsx
03/28/2022  02:27 PM           137,753 LUSID Excel - Manage your investment strategies.xlsx
03/28/2022  02:27 PM           184,013 LUSID Excel - Setting up your IBOR.xlsx
03/28/2022  02:27 PM           136,632 LUSID Excel - Setting up your market data.xlsx
03/28/2022  02:22 PM            22,576 Pandas(only structured datas).ipynb
               8 File(s)        912,825 bytes
               3 Dir(s)  18,062,102,528 bytes free

In [26]:
pd.read_excel('LUSID Excel - Manage Orders.xlsx',sheet_name = "Allocations")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,NaN,This sheet allows you to manage Allocations:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,1. ListAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2. GetAllocation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,3. UpsertAllocations,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,NaN,Code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,NaN,MyAllocation001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64,NaN,NaN,MyAllocation002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
df = pd.ExcelFile('LUSID Excel - Manage Orders.xlsx')
df.sheet_names #check all the sheets in the excel file

['Executions', 'Orders', 'Allocations', 'Placements', 'Blocks']

In [32]:
for i in df.sheet_names:
    x = pd.read_excel('LUSID Excel - Manage Orders.xlsx',sheet_name = i)
    print(x)

    Unnamed: 0                                   Unnamed: 1  \
0          NaN  This sheet allows you to manage executions:
1          NaN                           1. List executions
2          NaN                             2. Get execution
3          NaN                         3. Upsert executions
4          NaN                                          NaN
..         ...                                          ...
65         NaN                                          NaN
66         NaN                                          NaN
67         NaN                                          NaN
68         NaN                                          NaN
69         NaN                                          NaN

           Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7  \
0                 NaN        NaN        NaN        NaN        NaN        NaN
1                 NaN        NaN        NaN        NaN        NaN        NaN
2                 NaN        NaN        NaN        NaN        NaN        NaN
3                 NaN        NaN        NaN        NaN        NaN        NaN
4                 NaN        NaN        NaN        NaN        NaN        NaN
..                ...        ...        ...        ...        ...        ...
65                NaN        NaN        NaN        NaN        NaN        NaN
66                NaN        NaN        NaN        NaN        NaN        NaN
67                NaN        NaN        NaN        NaN        NaN        NaN
68               Code        NaN        NaN        NaN        NaN        NaN
69  MyExecutionCode01        NaN        NaN        NaN        NaN        NaN

   Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13  \
0         NaN        NaN         NaN         NaN         NaN         NaN
1         NaN        NaN         NaN         NaN         NaN         NaN
2         NaN        NaN         NaN         NaN         NaN         NaN
3         NaN        NaN         NaN         NaN         NaN         NaN
4         NaN        NaN         NaN         NaN         NaN         NaN
..        ...        ...         ...         ...         ...         ...
65        NaN        NaN         NaN         NaN         NaN         NaN
66        NaN        NaN         NaN         NaN         NaN         NaN
67        NaN        NaN         NaN         NaN         NaN         NaN
68        NaN        NaN         NaN         NaN         NaN         NaN
69        NaN        NaN         NaN         NaN         NaN         NaN

   Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17 Unnamed: 18
0          NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN
2          NaN         NaN         NaN         NaN         NaN
3          NaN         NaN         NaN         NaN         NaN
4          NaN         NaN         NaN         NaN         NaN
..         ...         ...         ...         ...         ...
65         NaN         NaN         NaN         NaN         NaN
66         NaN         NaN         NaN         NaN         NaN
67         NaN         NaN         NaN         NaN         NaN
68         NaN         NaN         NaN         NaN         NaN
69         NaN         NaN         NaN         NaN         NaN

[70 rows x 19 columns]
    Unnamed: 0                               Unnamed: 1     Unnamed: 2  \
0          NaN  This sheet allows you to manage Orders:            NaN
1          NaN                            1. ListOrders            NaN
2          NaN                              2. Getorder            NaN
3          NaN                          3. UpsertOrders            NaN
4          NaN                                      NaN            NaN
..         ...                                      ...            ...
66         NaN                                      NaN            NaN
67         NaN                                      NaN            NaN
68         NaN                                      NaN           Code
69         NaN                                      NaN  MyOrderCode02
70         NaN                                      NaN  MyOrderCode01

   Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN
2         NaN        NaN        NaN        NaN        NaN        NaN
3         NaN        NaN        NaN        NaN        NaN        NaN
4         NaN        NaN        NaN        NaN        NaN        NaN
..        ...        ...        ...        ...        ...        ...
66        NaN        NaN        NaN        NaN        NaN        NaN
67        NaN        NaN        NaN        NaN        NaN        NaN
68        NaN        NaN        NaN        NaN        NaN        NaN
69        NaN        NaN        NaN        NaN        NaN        NaN
70        NaN        NaN        NaN        NaN        NaN        NaN

   Unnamed: 9  ... Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16  \
0         NaN  ...         NaN         NaN         NaN         NaN
1         NaN  ...         NaN         NaN         NaN         NaN
2         NaN  ...         NaN         NaN         NaN         NaN
3         NaN  ...         NaN         NaN         NaN         NaN
4         NaN  ...         NaN         NaN         NaN         NaN
..        ...  ...         ...         ...         ...         ...
66        NaN  ...         NaN         NaN         NaN         NaN
67        NaN  ...         NaN         NaN         NaN         NaN
68        NaN  ...         NaN         NaN         NaN         NaN
69        NaN  ...         NaN         NaN         NaN         NaN
70        NaN  ...         NaN         NaN         NaN         NaN

   Unnamed: 17 Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN
2          NaN         NaN         NaN         NaN         NaN         NaN
3          NaN         NaN         NaN         NaN         NaN         NaN
4          NaN         NaN         NaN         NaN         NaN         NaN
..         ...         ...         ...         ...         ...         ...
66         NaN         NaN         NaN         NaN         NaN         NaN
67         NaN         NaN         NaN         NaN         NaN         NaN
68         NaN         NaN         NaN         NaN         NaN         NaN
69         NaN         NaN         NaN         NaN         NaN         NaN
70         NaN         NaN         NaN         NaN         NaN         NaN

[71 rows x 23 columns]
    Unnamed: 0                                    Unnamed: 1       Unnamed: 2  \
0          NaN  This sheet allows you to manage Allocations:              NaN
1          NaN                            1. ListAllocations              NaN
2          NaN                              2. GetAllocation              NaN
3          NaN                          3. UpsertAllocations              NaN
4          NaN                                           NaN              NaN
..         ...                                           ...              ...
60         NaN                                           NaN              NaN
61         NaN                                           NaN              NaN
62         NaN                                           NaN             Code
63         NaN                                           NaN  MyAllocation001
64         NaN                                           NaN  MyAllocation002

   Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN
2         NaN        NaN        NaN        NaN        NaN        NaN
3         NaN        NaN        NaN        NaN        NaN        NaN
4         NaN        NaN        NaN        NaN        NaN        NaN
..        ...        ...        ...        ...        ...        ...
60        NaN        NaN        NaN        NaN        NaN        NaN
61        NaN        NaN        NaN        NaN        NaN        NaN
62        NaN        NaN        NaN        NaN        NaN        NaN
63        NaN        NaN        NaN        NaN        NaN        NaN
64        NaN        NaN        NaN        NaN        NaN        NaN

   Unnamed: 9  ... Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15  \
0         NaN  ...         NaN         NaN         NaN         NaN
1         NaN  ...         NaN         NaN         NaN         NaN
2         NaN  ...         NaN         NaN         NaN         NaN
3         NaN  ...         NaN         NaN         NaN         NaN
4         NaN  ...         NaN         NaN         NaN         NaN
..        ...  ...         ...         ...         ...         ...
60        NaN  ...         NaN         NaN         NaN         NaN
61        NaN  ...         NaN         NaN         NaN         NaN
62        NaN  ...         NaN         NaN         NaN         NaN
63        NaN  ...         NaN         NaN         NaN         NaN
64        NaN  ...         NaN         NaN         NaN         NaN

   Unnamed: 16 Unnamed: 17 Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21
0          NaN         NaN         NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN         NaN         NaN
2          NaN         NaN         NaN         NaN         NaN         NaN
3          NaN         NaN         NaN         NaN         NaN         NaN
4          NaN         NaN         NaN         NaN         NaN         NaN
..         ...         ...         ...         ...         ...         ...
60         NaN         NaN         NaN         NaN         NaN         NaN
61         NaN         NaN         NaN         NaN         NaN         NaN
62         NaN         NaN         NaN         NaN         NaN         NaN
63         NaN         NaN         NaN         NaN         NaN         NaN
64         NaN         NaN         NaN         NaN         NaN         NaN

[65 rows x 22 columns]

    Unnamed: 0                                   Unnamed: 1    Unnamed: 2  \
0          NaN  This sheet allows you to manage Placements:           NaN
1          NaN                            1. ListPlacements           NaN
2          NaN                              2. GetPlacement           NaN
3          NaN                          3. UpsertPlacements           NaN
4          NaN                                          NaN           NaN
..         ...                                          ...           ...
58         NaN                                          NaN           NaN
59         NaN                                          NaN           NaN
60         NaN                                          NaN           NaN
61         NaN                                          NaN          Code
62         NaN                                          NaN  Placement001

   Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6 Unnamed: 7 Unnamed: 8  \
0         NaN        NaN        NaN        NaN        NaN        NaN
1         NaN        NaN        NaN        NaN        NaN        NaN
2         NaN        NaN        NaN        NaN        NaN        NaN
3         NaN        NaN        NaN        NaN        NaN        NaN
4         NaN        NaN        NaN        NaN        NaN        NaN
..        ...        ...        ...        ...        ...        ...
58        NaN        NaN        NaN        NaN        NaN        NaN
59        NaN        NaN        NaN        NaN        NaN        NaN
60        NaN        NaN        NaN        NaN        NaN        NaN
61        NaN        NaN        NaN        NaN        NaN        NaN
62        NaN        NaN        NaN        NaN        NaN        NaN

   Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14  \
0         NaN         NaN         NaN         NaN         NaN         NaN
1         NaN         NaN         NaN         NaN         NaN         NaN
2         NaN         NaN         NaN         NaN         NaN         NaN
3         NaN         NaN         NaN         NaN         NaN         NaN
4         NaN         NaN         NaN         NaN         NaN         NaN
..        ...         ...         ...         ...         ...         ...
58        NaN         NaN         NaN         NaN         NaN         NaN
59        NaN         NaN         NaN         NaN         NaN         NaN
60        NaN         NaN         NaN         NaN         NaN         NaN
61        NaN         NaN         NaN         NaN         NaN         NaN
62        NaN         NaN         NaN         NaN         NaN         NaN

   Unnamed: 15 Unnamed: 16 Unnamed: 17 Unnamed: 18
0          NaN         NaN         NaN         NaN
1          NaN         NaN         NaN         NaN
2          NaN         NaN         NaN         NaN
3          NaN         NaN         NaN         NaN
4          NaN         NaN         NaN         NaN
..         ...         ...         ...         ...
58         NaN         NaN         NaN         NaN
59         NaN         NaN         NaN         NaN
60         NaN         NaN         NaN         NaN
61         NaN         NaN         NaN         NaN
62         NaN         NaN         NaN         NaN

[63 rows x 19 columns]
    Unnamed: 0                               Unnamed: 1  \
0          NaN  This sheet allows you to manage Blocks:
1          NaN                            1. ListBlocks
2          NaN                              2. GetBlock
3          NaN                          3. UpsertBlocks
4          NaN                                      NaN
5          NaN                                      NaN
6          NaN                                      NaN
7          NaN                                      NaN
8          NaN                  1. Get a list of blocks
9          NaN                                      NaN
10         NaN                                    asAt:
11         NaN                                      NaN
12         NaN                                  filter:
13         NaN                                      NaN
14         NaN                            propertyKeys:
15         NaN                                      NaN
16         NaN                                      NaN
17         NaN                                      NaN
18         NaN                                      NaN
19         NaN                                      NaN
20         NaN                                      NaN
21         NaN                                      NaN
22         NaN                                      NaN
23         NaN                                      NaN
24         NaN                                      NaN
25         NaN                                      NaN
26         NaN                                      NaN
27         NaN                                      NaN
28         NaN                                      NaN
29         NaN                                      NaN
30         NaN                                      NaN
31         NaN                  2. Get a specific block
32         NaN                                      NaN
33         NaN                                   scope:
34         NaN                                      NaN
35         NaN                                    code:
36         NaN                                      NaN
37         NaN                                    asAt:
38         NaN                                      NaN
39         NaN                            propertyKeys:
40         NaN                                      NaN
41         NaN                                      NaN
42         NaN                                      NaN
43         NaN                                      NaN
44         NaN                                      NaN
45         NaN                         3. Upsert blocks
46         NaN                                      NaN
47         NaN    Add blocks using the following table:
48         NaN                                      NaN
49         NaN                                      NaN
50         NaN                                      NaN
51         NaN                                      NaN
52         NaN                                      NaN
53         NaN                                      NaN
54         NaN                                      NaN
55         NaN                                      NaN
56         NaN                                      NaN
57         NaN                                      NaN
58         NaN                                      NaN

                               Unnamed: 2        Unnamed: 3  \
0                                     NaN               NaN
1                                     NaN               NaN
2                                     NaN               NaN
3                                     NaN               NaN
4                                     NaN               NaN
5                                     NaN               NaN
6                                     NaN               NaN
7                                     NaN               NaN
8                                     NaN               NaN
9                                     NaN               NaN
10                                    NaN               NaN
11                                    NaN               NaN
12                         quantity gt 50               NaN
13                                    NaN               NaN
14  Block/MyScope/SomeOrderEntityProperty               NaN
15                                    NaN               NaN
16                               Id Scope           Id Code
17                             TestScope2  orderEntityCode2
18                              TestScope      OrderEntity6
19                              TestScope      OrderEntity1
20                              TestScope      OrderEntity5
21                              TestScope      OrderEntity2
22                              TestScope      OrderEntity4
23                              TestScope      OrderEntity3
24                              TestScope  orderEntityCode1
25                              TestScope   BLOC_1310500833
26                              TestScope    BLOC_949780324
27                    TestScopeOrderGraph   BLOC_1842506452
28                              [More...]         [More...]
29                                    NaN               NaN
30                                    NaN               NaN
31                                    NaN               NaN
32                                    NaN               NaN
33                              TestScope               NaN
34                                    NaN               NaN
35                           OrderEntity1               NaN
36                                    NaN               NaN
37                                    NaN               NaN
38                                    NaN               NaN
39  Block/MyScope/SomeOrderEntityProperty               NaN
40                                    NaN               NaN
41                               Id Scope           Id Code
42                              TestScope      OrderEntity1
43                                    NaN               NaN
44                                    NaN               NaN
45                                    NaN               NaN
46                                    NaN               NaN
47                                    NaN               NaN
48                                    NaN               NaN
49                               Id Scope           Id Code
50                              TestScope        MyOrder001
51                                    NaN               NaN
52                                    NaN               NaN
53                                    NaN               NaN
54                                    NaN               NaN
55                                    NaN               NaN
56                                    NaN               NaN
57                                   Code               NaN
58                             MyOrder001               NaN

                           Unnamed: 4  \
0                                 NaN
1                                 NaN
2                                 NaN
3                                 NaN
4                                 NaN
5                                 NaN
6                                 NaN
7                                 NaN
8                                 NaN
9                                 NaN
10                                NaN
11                                NaN
12                                NaN
13                                NaN
14                                NaN
15                                NaN
16                           OrderIds
17               TestScope2:testOrder
18                TestScope:testOrder
19                TestScope:testOrder
20                TestScope:testOrder
21                TestScope:testOrder
22                TestScope:testOrder
23                TestScope:testOrder
24                TestScope:testOrder
25            TestScope:ORD_805415329
26             TestScope:ORD_98041040
27  TestScopeOrderGraph:ORD_265037669
28                          [More...]
29                                NaN
30                                NaN
31                                NaN
32                                NaN
33                                NaN
34                                NaN
35                                NaN
36                                NaN
37                                NaN
38                                NaN
39                                NaN
40                                NaN
41                           OrderIds
42                TestScope:testOrder
43                                NaN
44                                NaN
45                                NaN
46                                NaN
47                                NaN
48                                NaN
49                           OrderIds
50                TestScope:testOrder
51                                NaN
52                                NaN
53                                NaN
54                                NaN
55                                NaN
56                                NaN
57                                NaN
58                                NaN

                                           Unnamed: 5         Unnamed: 6  \
0                                                 NaN                NaN
1                                                 NaN                NaN
2                                                 NaN                NaN
3                                                 NaN                NaN
4                                                 NaN                NaN
5                                                 NaN                NaN
6                                                 NaN                NaN
7                                                 NaN                NaN
8                                                 NaN                NaN
9                                                 NaN                NaN
10                                                NaN                NaN
11                                                NaN                NaN
12                                                NaN                NaN
13                                                NaN                NaN
14                                                NaN                NaN
15                                                NaN                NaN
16                              InstrumentIdentifiers  LusidInstrumentId
17                     Instrument/default/Name:ABC123      LUID_ZZZZZZZZ
18                     Instrument/default/Figi:INSTR1      LUID_ZZZZZZZZ
19                     Instrument/default/Figi:INSTR1      LUID_ZZZZZZZZ
20                     Instrument/default/Figi:INSTR1      LUID_ZZZZZZZZ
21                     Instrument/default/Figi:INSTR1      LUID_ZZZZZZZZ
22                     Instrument/default/Figi:INSTR1      LUID_ZZZZZZZZ
23                     Instrument/default/Figi:INSTR1      LUID_ZZZZZZZZ
24                     Instrument/default/Name:ABC123      LUID_ZZZZZZZZ
25  Instrument/default/Ticker:AMZN,Instrument/defa...      LUID_3QJOY75Q
26  Instrument/default/Ticker:VOD,Instrument/defau...      LUID_LP8MS5OS
27  Instrument/default/Ticker:AAPL,Instrument/defa...      LUID_JUE15W3W
28                                          [More...]          [More...]
29                                                NaN                NaN
30                                                NaN                NaN
31                                                NaN                NaN
32                                                NaN                NaN
33                                                NaN                NaN
34                                                NaN                NaN
35                                                NaN                NaN
36                                                NaN                NaN
37                                                NaN                NaN
38                                                NaN                NaN
39                                                NaN                NaN
40                                                NaN                NaN
41                              InstrumentIdentifiers  LusidInstrumentId
42                     Instrument/default/Figi:INSTR1      LUID_ZZZZZZZZ
43                                                NaN                NaN
44                                                NaN                NaN
45                                                NaN                NaN
46                                                NaN                NaN
47                                                NaN                NaN
48                                                NaN                NaN
49                                Instrument Id Types     Instrument Ids
50                            Instrument/default/Figi             INSTR1
51                                                NaN                NaN
52                                                NaN                NaN
53                                                NaN                NaN
54                                                NaN                NaN
55                                                NaN                NaN
56                                                NaN                NaN
57                                                NaN                NaN
58                                                NaN                NaN

   Unnamed: 7 Unnamed: 8         Unnamed: 9  Unnamed: 10          Unnamed: 11  \
0         NaN        NaN                NaN          NaN                  NaN
1         NaN        NaN                NaN          NaN                  NaN
2         NaN        NaN                NaN          NaN                  NaN
3         NaN        NaN                NaN          NaN                  NaN
4         NaN        NaN                NaN          NaN                  NaN
5         NaN        NaN                NaN          NaN                  NaN
6         NaN        NaN                NaN          NaN                  NaN
7         NaN        NaN                NaN          NaN                  NaN
8         NaN        NaN                NaN          NaN                  NaN
9         NaN        NaN                NaN          NaN                  NaN
10        NaN        NaN                NaN          NaN                  NaN
11        NaN        NaN                NaN          NaN                  NaN
12        NaN        NaN                NaN          NaN                  NaN
13        NaN        NaN                NaN          NaN                  NaN
14        NaN        NaN                NaN          NaN                  NaN
15        NaN        NaN                NaN          NaN                  NaN
16   Quantity       Side               Type  TimeInForce          CreatedDate
17        100        Buy                GTC       Market  2020-10-10 00:00:00
18        100        Buy                GTC       Market  2020-10-10 00:00:00
19        100        Buy                GTC       Market  2020-10-10 00:00:00
20        100        Buy                GTC       Market  2020-10-10 00:00:00
21        100        Buy                GTC       Market  2020-10-10 00:00:00
22        100        Buy                GTC       Market  2020-10-10 00:00:00
23        100        Buy                GTC       Market  2020-10-10 00:00:00
24        100        Buy                GTC       Market  2020-10-10 00:00:00
25       2342        Buy  Good Til Canceled        Limit  2020-01-01 01:02:03
26       2189        Buy  Good Til Canceled        Limit  2020-01-01 01:02:03
27       2190        Buy  Good Til Canceled        Limit  2020-01-01 01:02:03
28  [More...]  [More...]          [More...]    [More...]            [More...]
29        NaN        NaN                NaN          NaN                  NaN
30        NaN        NaN                NaN          NaN                  NaN
31        NaN        NaN                NaN          NaN                  NaN
32        NaN        NaN                NaN          NaN                  NaN
33        NaN        NaN                NaN          NaN                  NaN
34        NaN        NaN                NaN          NaN                  NaN
35        NaN        NaN                NaN          NaN                  NaN
36        NaN        NaN                NaN          NaN                  NaN
37        NaN        NaN                NaN          NaN                  NaN

In [35]:
#In github, go to raw and then you can directly paste the link to read the csv file
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [2]:
import pandas as pd
df = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')
df

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [3]:
df[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [5]:
type(df[0])

pandas.core.frame.DataFrame

In [6]:
df1 = df[0]

In [7]:
df1.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [8]:
df1.dtypes

Rk        object
Player    object
Pos       object
Age       object
Tm        object
G         object
GS        object
MP        object
FG        object
FGA       object
FG%       object
3P        object
3PA       object
3P%       object
2P        object
2PA       object
2P%       object
eFG%      object
FT        object
FTA       object
FT%       object
ORB       object
DRB       object
TRB       object
AST       object
STL       object
BLK       object
TOV       object
PF        object
PTS       object
dtype: object

In [9]:
df1.to_csv('NBA.csv')

In [10]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 8A66-F804

 Directory of C:\Users\Rokaya Neeraj\Full Stack Data Science\Python\Da13-Pandas

03/29/2022  12:08 PM    <DIR>          .
03/29/2022  12:08 PM    <DIR>          ..
03/28/2022  01:41 PM    <DIR>          .ipynb_checkpoints
03/28/2022  02:27 PM           161,651 LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx
03/28/2022  02:27 PM           161,410 LUSID Excel - Maintain a product in multiple currencies and share classes.xlsx
03/28/2022  02:27 PM            24,471 LUSID Excel - Manage instruments with economic definitions.xlsx
03/28/2022  02:27 PM            84,319 LUSID Excel - Manage Orders.xlsx
03/28/2022  02:27 PM           137,753 LUSID Excel - Manage your investment strategies.xlsx
03/28/2022  02:27 PM           184,013 LUSID Excel - Setting up your IBOR.xlsx
03/28/2022  02:27 PM           136,632 LUSID Excel - Setting up your market data.xlsx
03/29/2022  12:08 PM            81,551 NBA.csv
03/29/2022  12:08 PM           113,175 Pandas(only structured datas).ipynb
               9 File(s)      1,084,975 bytes
               3 Dir(s)  20,342,652,928 bytes free

In [ ]:
df1.to_csv('NBA.csv')

In [26]:
z = pd.read_csv("NBA.csv")
z

,Unnamed: 0,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,...,.784,79,222,301,68,27,22,60,147,398
1,1,2,Jordan Adams,SG,20,MEM,30,0,248,35,...,.609,9,19,28,16,16,7,14,24,94
2,2,3,Steven Adams,C,21,OKC,70,67,1771,217,...,.502,199,324,523,66,38,86,99,222,537
3,3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,...,.579,23,54,77,15,4,9,9,30,60
4,4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,...,.655,127,284,411,173,124,25,117,171,1071
671,671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,...,.682,75,170,245,135,86,17,75,115,685
672,672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,...,.606,52,114,166,38,38,8,42,56,386
673,673,491,Cody Zeller,C,22,CHO,62,45,1487,172,...,.774,97,265,362,100,34,49,62,156,472
674,674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,...,.823,146,319,465,113,18,52,76,205,833

In [25]:
import pandas as pd
df = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')
df

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [21]:
df1 = df[0]

In [22]:
df1.to_csv('NBA2.csv',index = False)

In [23]:
df1

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [30]:
l = pd.read_html('https://stats.espncricinfo.com/ci/engine/records/averages/batting.html?class=3;id=6;type=team')
l

[               Player       Span  Mat Inns NO  Runs   HS    Ave   BF      SR  \
 0          AB Agarkar  2006-2007    4    2  0    15   14   7.50   11  136.36
 1            KK Ahmed  2018-2019   14    1  1     1   1*      -    1  100.00
 2           S Aravind  2015-2015    1    -  -     -    -      -    -       -
 3            R Ashwin  2010-2021   51   11  7   123  31*  30.75  115  106.95
 4          Avesh Khan  2022-2022    2    -  -     -    -      -    -       -
 ..                ...        ...  ...  ... ..   ...  ...    ...  ...     ...
 92      R Vinay Kumar  2010-2013    9    1  1     2   2*      -    4   50.00
 93  Washington Sundar  2017-2021   31   11  4    47  14*   6.71   32  146.87
 94           SA Yadav  2021-2022   14   12  3   351   65  39.00  212  165.56
 95           UT Yadav  2012-2019    7    1  0     2    2   2.00    4   50.00
 96       Yuvraj Singh  2007-2017   58   51  9  1177  77*  28.02  863  136.38

    100 50  0  4s  6s
 0    0  0  0   2   0
 1    0  0  0   0   0
 2    -  -  -   -   -
 3    0  0  0  14   1
 4    -  -  -   -   -
 ..  .. .. ..  ..  ..
 92   0  0  0   0   0
 93   0  0  3   4   3
 94   0  4  1  32  20
 95   0  0  0   0   0
 96   0  8  1  77  74

 [97 rows x 15 columns],
                                                    0
 0  By default, the shading indicates records from...
 1  Adjust:  most recent  | past week  | past mont...,
                                                    0
 0  Records includes the following current or rece...
 1  India v Sri Lanka at Dharamsala, 3rd T20I, Feb...
 2  India v Sri Lanka at Dharamsala, 2nd T20I, Feb...
 3  India v Sri Lanka at Lucknow, 1st T20I, Feb 24...]

In [33]:
l[0].to_csv('criket.csv',index = False)

In [31]:
len(l)

3

In [32]:
l[1]

                                                   0
0  By default, the shading indicates records from...
1  Adjust:  most recent  | past week  | past mont...

In [43]:
#convering dictionary into dataframe
d = """
{"name": "Niraj Rokaya",
"email_id":"rokayaneeraj@gmail.com",
"tech":["ML","DL","CV","NLP","RL","BD","DA"],
"platform":["techneuron","kidsneuron","ineuron"]
}
""" #check json viewer in google and paste the data to validate

In [44]:
import json

In [45]:
result = json.loads(d)

In [47]:
result

{'name': 'Niraj Rokaya',
 'email_id': 'rokayaneeraj@gmail.com',
 'tech': ['ML', 'DL', 'CV', 'NLP', 'RL', 'BD', 'DA'],
 'platform': ['techneuron', 'kidsneuron', 'ineuron']}

In [51]:
pd.DataFrame(result) #if we remove NLP,RL,BD and Da than it will work

ValueError: All arrays must be of the same length

In [56]:
d1 = d = """
{"name": "Niraj Rokaya",
"email_id":"rokayaneeraj@gmail.com",
"tech":["ML","DL","CV"],
"platform":["techneuron","kidsneuron","ineuron"],
"random": []
}
"""

In [57]:
import json
x = json.loads(d1)
x

{'name': 'Niraj Rokaya',
 'email_id': 'rokayaneeraj@gmail.com',
 'tech': ['ML', 'DL', 'CV'],
 'platform': ['techneuron', 'kidsneuron', 'ineuron'],
 'random': []}

In [58]:
pd.DataFrame(x)

ValueError: All arrays must be of the same length

In [59]:
del x['random'] #deleting the empty list to match the number of data in the list

In [60]:
pd.DataFrame(x)

           name                email_id tech    platform
0  Niraj Rokaya  rokayaneeraj@gmail.com   ML  techneuron
1  Niraj Rokaya  rokayaneeraj@gmail.com   DL  kidsneuron
2  Niraj Rokaya  rokayaneeraj@gmail.com   CV     ineuron

In [1]:
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [2]:
import pandas as pd
pd.read_json(url)

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46570,1185906280,PR_kwDOAA0YD841SPuI,46570,POC For docker compose,...,2022-03-30 05:31:18+00:00,NaT,MEMBER,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,- [X] closes #46532 \r\n\r\nPOC using docker c...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46569,1185878561,I_kwDOAA0YD85GrxIh,46569,BUG: ENH: Allow callable for on_bad_lines in ...,...,2022-03-30 05:02:02+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46568,1185785553,PR_kwDOAA0YD841R1wW,46568,CLN/TYP: assorted,...,2022-03-30 04:06:44+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,None,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46567,1185751008,PR_kwDOAA0YD841RuBO,46567,BUG: groupby().rolling(freq) with monotonic da...,...,2022-03-30 04:43:24+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46061 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46566,1185480392,I_kwDOAA0YD85GqP7I,46566,BUG: Segmentation fault with groupby/transform,...,2022-03-29 22:42:05+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46565,1185340074,PR_kwDOAA0YD841QTBO,46565,TYP: setter for index/columns property-like (A...,...,2022-03-29 20:08:27+00:00,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,None,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46564,1185191491,PR_kwDOAA0YD841Pzhq,46564,Don't run GHA CI for Azure changes and vice-versa,...,2022-03-30 00:58:58+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46563,1184908880,PR_kwDOAA0YD841O3w7,46563,Backport PR #46558: CI: pre-commit autoupdate ...,...,2022-03-29 14:16:08+00:00,NaT,MEMBER,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46562,1184896816,PR_kwDOAA0YD841O1Mm,46562,tocsv_interval _categories,...,2022-03-29 13:43:10+00:00,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46297\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46561,1184875189,I_kwDOAA0YD85Gn8K1,46561,STYLE: add check to keep `black` version in sy...,...,2022-03-29 22:31:03+00:00,NaT,MEMBER,NaN,NaN,NaN,Might be possible to adapt\r\n\r\nhttps://gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46560,1184857243,I_kwDOAA0YD85Gn3yb,46560,API: numeric_only consistency,...,2022-03-29 13:21:52+00:00,NaT,MEMBER,NaN,NaN,NaN,Tracking issue for API consistency between all...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46556,1184681111,PR_kwDOAA0YD841OHMe,46556,Close FastParquet file even on error,...,2022-03-30 00:54:47+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46555\r\n- [ ] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46555,1184680680,I_kwDOAA0YD85GnMro,46555,BUG: read_parquet leaks file handles on error,...,2022-03-29 13:20:41+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46553,1184482464,I_kwDOAA0YD85GmcSg,46553,ENH: Compact result from named aggregation,...,2022-03-29 08:13:02+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,#### Is your feature request related to a prob...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46552,1184197156,I_kwDOAA0YD85GlWok,46552,BUG: Unexpected change of behavior on DataFra...,...,2022-03-29 02:03:29+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46551,1184130581,I_kwDOAA0YD85GlGYV,46551,BUG: Unexpected IndexingError when filtering w...,...,2022-03-29 00:09:43+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46549,1184051642,I_kwDOAA0YD85GkzG6,46549,BUG: MultiIndex KeyError message unreliable,...,2022-03-28 22:17:33+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46548,1184024032,PR_kwDOAA0YD841L7yn,46548,REGR: tests + whats new: boolean dtype in styl...,...,2022-03-29 11:27:37+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,### COMES AFTER #46501 \r\n\r\ncloses #46384,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46546,1183908098,PR_kwDOAA0YD841Lipq,46546,BUG: pd.concat with identical key leads to mul...,...,2022-03-29 23:03:37+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #46519 \r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46545,1183869246,I_kwDOAA0YD85GkGk-,46545,BUG: DataFrame.__setitem__: ValueError: Expect...,...,2022-03-28 19:10:12+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46544,1183850935,I_kwDOAA0YD85GkCG3,46544,BUG: `DataFrame.loc` is not consistent with `D...,...,2022-03-28 18:55:32+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46539,1183317929,I_kwDOAA0YD85Gh_-p,46539,BUG: pd.concat on DF with time series containi...,...,2022-03-28 11:55:50+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46538,1183041719,PR_kwDOAA0YD841Iq-a,46538,CI: Refactor sdist workflow and add setup-pyth...,...,2022-03-30 01:06:17+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Smaller version of https://github.com/pandas-d...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46534,1182645265,PR_kwDOAA0YD841HYFH,46534,TST: Add test with large shape to check_below_...,...,2022-03-29 23:03:22+00:00,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,The function in question didn't have any tests...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46532,1182629932,I_kwDOAA0YD85GfYAs,46532,ENH: Use docker compose,...,2022-03-27 19:02:25+00:00,NaT,MEMBER,NaN,NaN,NaN,The arrow project uses docker compose to make ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46527,1182538671,I_kwDOAA0YD85GfBuv,46527,PERF: groupby on an unsorted index slows to a ...,...,2022-03-27 14:14:00+00:00,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46524,1181927936,I_kwDOAA0YD85GcsoA,46524,ENH: Add numeric_only to groupby frame ops,...,2022-03-29 13:24:56+00:00,NaT,MEMBER,NaN,NaN,NaN,"Once #46072 is implemented, many groupby ops w...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46522,1181860650,PR_kwDOAA0YD841Euya,46522,ENH: consistency of input args for boundaries ...,...,2022-03-30 02:08:58+00:00,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #40245\r\n- [ ] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46521,1181801618,PR_kwDOAA0YD841Eh13,46521,TYP: Fix core/groupby/generic.py type ignores,...,2022-03-29 22:44:59+00:00,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,xref #37715\r\n\r\nTwo things to mention:\r\n\...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46519,1181554965,I_kwDOAA0YD85GbRkV,46519,"BUG: Result of `pd.concat([], keys=)` with ide...",...,2022-03-29 00:17:17+00:00,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN

### Trying to fecth user

In [3]:
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [4]:
data = requests.get(url)

In [5]:
data #indicates successful

In [6]:
data1 = data.json()

In [7]:
data1

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/46570',
  'id': 1185906280,
  'node_id': 'PR_kwDOAA0YD841SPuI',
  'number': 46570,
  'title': 'POC For docker compose',
  'user': {'login': 'WillAyd',
   'id': 609873,
   'node_id': 'MDQ6VXNlcjYwOTg3Mw==',
   'avatar_url': 'https://avatars.githubusercontent.com/u/609873?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/WillAyd',
   'html_url': 'https://github.com/WillAyd',
   'followers_url': 'https://api.github.com/users/WillAyd/followers',
   'following_url': 'https://api.github.com/users/WillAyd/following{/other_user}',
   'gists_url': 'https://api.github.com/users/WillAyd/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/WillAyd/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/WillAyd/subscriptions',
   'organizations_url': 'https://api.github.com/users/WillAyd/orgs',
   'repos_url': 'https://api.github.com/users/WillAyd/repos',
   'events_url': 'https://api.github.com/users/WillAyd/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/WillAyd/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 48070600,
    'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
    'name': 'CI',
    'color': 'a2bca7',
    'default': False,
    'description': 'Continuous Integration'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-03-30T05:31:11Z',
  'updated_at': '2022-03-30T05:31:18Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': True,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46570',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/46570',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/46570.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/46570.patch',
   'merged_at': None},
  'body': '- [X] closes #46532 \r\n\r\nPOC using docker compose, which is also used by the arrow project. \r\n\r\nThe idea here is that we can simply run `docker compose build db-testing` to build an image with postgres (can later add mysql) and our minimal development requirements then `docker compose run --rm db-testing` to run relevant tests. This can be done both by a developer as well as on GH actions.\r\n\r\nThis still needs a bit more work as it currently muddles user permissions on the host when building pandas\r\n\r\ncc @jonashaag who looks to have been doing some awesome work on CI lately',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/timeline',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46569',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46569/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46569/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46569/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/46569',
  'id': 1185878561,
  'node_id': 'I_kwDOAA0YD85GrxIh',
  'number': 46569,
  'title': 'BUG:  ENH: Allow callable for on_bad_lines in read_csv when engine="python" #45146',
  'user': {'login': 'kevinhodes',
   'id': 89279983,
   'node_id': 'MDQ6VXNlcjg5Mjc5OTgz',
   'avatar_url': 'https://avatars.githubusercontent.com/u/89279983?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/kevinhodes',
   'html_url': 'https://github.com/kevinhodes',
   'followers_url': 'https://api.github.com/users/kevinhodes/followers',
   'following_url': 'https://api.github.com/users/kevinhodes/following{/other_user}',
   'gists_url': 'https://api.github.com/users/kevinhodes/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/kevinhodes/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/kevinhodes/subscriptions',
   'organizations_url': 'https://api.github.com/users/kevinhodes/orgs',
   'repos_url': 'https://api.github.com/users/kevinhodes/repos',
   'events_url': 'https://api.github.com/users/kevinhodes/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/kevinhodes/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-03-30T05:02:02Z',
  'updated_at': '2022-03-30T05:02:02Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': '### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\n\r\nlst = []\r\n\r\n\r\ndef failed_line(bad_line: list[str]) -> list[str]:\r\n    print("failed line")\r\n    lst.append(bad_line)\r\n    return lst\r\n\r\n\r\nif __name__ == \'__main__\':\r\n    dtypes = {\r\n        "CV_CCT": object,\r\n        "C_NOMBRE": object,\r\n        "CV_TIPO": float,\r\n        "C_TIPO": object,\r\n        "CV_ADMINISTRATIVA": object,\r\n        "C_ADMINISTRATIVA": object,\r\n        "CV_ESTATUS": int,\r\n        "C_ESTATUS": object,\r\n        "F_FUNDACION": object,\r\n        "INMUEBLE_CV_INMUEBLE": object,\r\n        "INMUEBLE_CV_VIALIDAD_PRINCIPAL": int,\r\n        "INMUEBLE_C_VIALIDAD_PRINCIPAL": object,\r\n        "INMUEBLE_CV_VIALIDAD_DERECHA": int,\r\n        "INMUEBLE_C_VIALIDAD_DERECHA": object,\r\n        "INMUEBLE_CV_VIALIDAD_IZQUIERDA": int,\r\n        "INMUEBLE_C_VIALIDAD_IZQUIERDA": object,\r\n        "INMUEBLE_CV_VIALIDAD_POSTERIOR": int,\r\n        "INMUEBLE_C_VIALIDAD_POSTERIOR": object,\r\n        "INMUEBLE_N_EXTNUM": int,\r\n        "INMUEBLE_C_EXTALF": object,\r\n        "INMUEBLE_N_INTNUM": int,\r\n        "INMUEBLE_C_INTALF": object,\r\n        "INMUEBLE_CV_ENT": object,\r\n        "INMUEBLE_C_NOM_ENT": object,\r\n        "INMUEBLE_CV_MUN": object,\r\n        "INMUEBLE_C_NOM_MUN": object,\r\n        "INMUEBLE_CV_LOC": object,\r\n        "INMUEBLE_C_NOM_LOC": object,\r\n        "INMUEBLE_CV_ASEN": object,\r\n        "INMUEBLE_C_NOM_ASEN": object,\r\n        "INMUEBLE_CV_CODIGO_POSTAL": object,\r\n        "INMUEBLE_C_DESC_UBICACION": object,\r\n        "INMUEBLE_LATITUD": float,\r\n        "INMUEBLE_LONGITUD": float,\r\n        "SOSTENIMIENTO_CV_CONTROL": int,\r\n        "SOSTENIMIENTO_C_CONTROL": object,\r\n        "SOSTENIMIENTO_CV_SUBCONTROL": int,\r\n        "SOSTENIMIENTO_C_SUBCONTROL": object,\r\n        "SOSTENIMIENTO_CV_DEPENDENCIAN1": int,\r\n        "SOSTENIMIENTO_C_DEPENDENCIAN1": object,\r\n        "SOSTENIMIENTO_CV_DEPENDENCIAN2": int,\r\n        "SOSTENIMIENTO_C_DEPENDENCIAN2": object,\r\n        "SOSTENIMIENTO_CV_DEPENDENCIAN3": int,\r\n        "SOSTENIMIENTO_C_DEPENDENCIAN3": object,\r\n        "SOSTENIMIENTO_CV_DEPENDENCIAN4": int,\r\n        "SOSTENIMIENTO_C_DEPENDENCIAN4": object,\r\n        "SOSTENIMIENTO_CV_DEPENDENCIAN5": int,\r\n        "SOSTENIMIENTO_C_DEPENDENCIAN5": object,\r\n        "SOSTENIMIENTO_CV_SERVICIO": object,\r\n        "SOSTENIMIENTO_C_SERVICIO": object,\r\n        "DEPOPERATIVA_CV_DEPENDENCIAN1": int,\r\n        "DEPOPERATIVA_C_DEPENDENCIAN1": object,\r\n        "DEPOPERATIVA_CV_DEPENDENCIAN2": int,\r\n        "DEPOPERATIVA_C_DEPENDENCIAN2": object,\r\n        "DEPOPERATIVA_CV_DEPENDENCIAN3": int,\r\n        "DEPOPERATIVA_C_DEPENDENCIAN3": object,\r\n        "DEPOPERATIVA_CV_DEPENDENCIAN4": int,\r\n        "DEPOPERATIVA_C_DEPENDENCIAN4": object,\r\n        "DEPOPERATIVA_CV_DEPENDENCIAN5": int,\r\n        "DEPOPERATIVA_C_DEPENDENCIAN5": object,\r\n        "CONTACTO_CV_CARGO": int,\r\n        "CONTACTO_C_CARGO": object,\r\n        "CONTACTO_CV_TIPODIRECTOR": int,\r\n        "CONTACTO_C_TIPODIRECTOR": object,\r\n        "CONTACTO_C_ASOCIACION": object,\r\n        "CONTACTO_C_CURP": object,\r\n        "CONTACTO_C_RFC": object,\r\n        "CONTACTO_C_NOMBRE": object,\r\n        "CONTACTO_C_APELLIDO1": object,\r\n        "CONTACTO_C_APELLIDO2": object,\r\n        "CONTACTO_C_TELEFONO": object,\r\n        "CONTACTO_C_CELULAR": object,\r\n        "CONTACTO_C_EMAIL": object,\r\n        "CONTACTO_C_EXTENSION": object,\r\n        "CONTACTO_C_PWEB": object,\r\n        "SERREG_CV_CCT": object,\r\n        "JEFSEC_CV_CCT": object,\r\n        "SUPERVISION_CV_CCT": object,\r\n        "C_TUNO_1": object,\r\n        "C_TUNO_2": object,\r\n        "C_TUNO_3": object,\r\n        "TIPONIVELSUB_CV_SERVICION1": int,\r\n        "TIPONIVELSUB_C_SERVICION1": object,\r\n        "TIPONIVELSUB_CV_SERVICION2": int,\r\n        "TIPONIVELSUB_C_SERVICION2": object,\r\n        "TIPONIVELSUB_CV_SERVICION3": int,\r\n        "TIPONIVELSUB_C_SERVICION3": object,\r\n        "C_SERVICIO_CAM": object,\r\n        "CARACTERISTCA_CV_CARACTERIZAN1": int,\r\n        "CARACTERISTCA_C_CARACTERIZAN1": object,\r\n        "CARACTERISTCA_CV_CARACTERIZAN2": int,\r\n        "CARACTERISTCA_C_CARACTERIZAN2": object,\r\n        "Unnamed: 92": object\r\n    }\r\n\r\n    df = pd.read_csv("cct15_bad.csv", encoding=\'ansi\', dtype=dtypes, on_bad_lines=failed_line, engine=\'python\')\n```\n\n\n### Issue Description\n\nfailed_line() never gets fired.\n\n### Expected Behavior\n\nfailed_line() to get fired.\n\n### Installed Versions\n\n<details>\r\n\r\nWindows 10\r\npython 3.10\r\npandas 1.4.1\r\n\r\n</details>\r\n[cct15_bad.zip](https://github.com/pandas-dev/pandas/files/8377144/cct15_bad.zip)\r\n\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46569/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46569/timeline',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46568',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46568/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46568/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46568/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/46568',
  'id': 1185785553,
  'node_id': 'PR_kwDOAA0YD841R1wW',
  'number': 46568,
  'title': 'CLN/TYP: assorted',
  'user': {'login': 'jbrockmendel',
   'id': 8078968,
   'node_id': 'MDQ6VXNlcjgwNzg5Njg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/jbrockmendel',
   'html_url': 'https://github.com/jbrockmendel',
   'followers_url': 'https://api.github.com/users/jbrockmendel/followers',
   'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}',
   'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions',
   'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs',
   'repos_url': 'https://api.github.com/users/jbrockmendel/repos',
   'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-03-30T02:41:10Z',
  'updated_at': '2022-03-30T04:06:44Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46568',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/46568',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/46568.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/46568.patch',
   'merged_at': None},
  'body': None,
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46568/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46568/timeline',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46567',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46567/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46567/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46567/events',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/46567',
  'id': 1185751008,
  'node_id': 'PR_kwDOAA0YD841RuBO',
  'number': 46567,
  'title': 'BUG: groupby().rolling(freq) with monotonic dates within groups #46065 ',
  'user': {'login': 'mroeschke',
   'id': 10647082,
   'node_id': 'MDQ6VXNlcjEwNjQ3MDgy',
   'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/mroeschke',
   'html_url': 'https://github.com/mroeschke',
   'followers_url': 'https://api.github.com/users/mroeschke/followers',
   'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}',
   'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions',
   'organizations_url': 'https://api.github.com/users/mroeschke/orgs',
   'repos_url': 'https://api.github.com/users/mroeschke/repos',
   'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/mroeschke/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1045950827,
    'node_id': 'MDU6TGFiZWwxMDQ1OTUwODI3',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Window',
    'name': 'Window',
    'color': 'd4c5f9',
    'default': False,
    'description': 'rolling, ewma, expanding'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94',
   'html_url': 'https://github.com/pandas-dev/pandas/milestone/94',
   'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/94/labels',
   'id': 7667127,
   'node_id': 'MI_kwDOAA0YD84AdP23',
   'number': 94,
   'title': '1.4.2',
   'description': 'on-merge: backport to 1.4.x',
   'creator': {'login': 'simonjayhawkins',
    'id': 13159005,
    'node_id': 'MDQ6VXNlcjEzMTU5MDA1',
    'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/simonjayhawkins',
    'html_url': 'https://github.com/simonjayhawkins',
    'followers_url': 'https://api.github.com/users/simonjayhawkins/followers',
    'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}',
    'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions',
    'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs',
    'repos_url': 'https://api.github.com/users/simonjayhawkins/repos',
    'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events',
    'type': 'User',
    'site_admin': False},
   'open_issues': 12,
   'closed_issues': 79,
   'state': 'open',
   'created_at': '2022-02-11T09:43:27Z',
   'updated_at': '2022-03-30T02:15:00Z',
   'due_on': '2022-03-05T08:00:00Z',
   'closed_at': None},
  'comments': 0,
  'created_at': '2022-03-30T02:15:00Z',
  'updated_at': '2022-03-30T04:43:24Z',
  'closed_at': None,
  'author_association': 'MEMBER',
  'active_lock_reason': None,
  'draft': False,
  'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46567',
   'html_url': 'https://github.com/pandas-dev/pandas/pull/46567',
   'diff_url': 'https://github.com/pandas-dev/pandas/pull/46567.diff',
   'patch_url': 'https://github.com/pandas-dev/pandas/pull/46567.patch',
   'merged_at': None},
  'body': '- [x] closes #46061 (Replace xxxx with the Github issue number)\r\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\r\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\r\n- [x] Added an entry in the latest `doc/source/whatsnew/v1.4.2.rst` file if fixing a bug or adding a new feature.\r\n\r\nRestored version in https://github.com/pandas-dev/pandas/pull/46065 as there is some support for the bug fix despite the performance hit.',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46567/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46567/timeline',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46566',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46566/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46566/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46566/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/46566',
  'id': 1185480392,
  'node_id': 'I_kwDOAA0YD85GqP7I',
  'number': 46566,

In [8]:
len(data1) #shows the number of dictionary present

30

In [23]:
data1[0]

{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570',
 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/labels{/name}',
 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/comments',
 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/events',
 'html_url': 'https://github.com/pandas-dev/pandas/pull/46570',
 'id': 1185906280,
 'node_id': 'PR_kwDOAA0YD841SPuI',
 'number': 46570,
 'title': 'POC For docker compose',
 'user': {'login': 'WillAyd',
  'id': 609873,
  'node_id': 'MDQ6VXNlcjYwOTg3Mw==',
  'avatar_url': 'https://avatars.githubusercontent.com/u/609873?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/WillAyd',
  'html_url': 'https://github.com/WillAyd',
  'followers_url': 'https://api.github.com/users/WillAyd/followers',
  'following_url': 'https://api.github.com/users/WillAyd/following{/other_user}',
  'gists_url': 'https://api.github.com/users/WillAyd/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/WillAyd/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/WillAyd/subscriptions',
  'organizations_url': 'https://api.github.com/users/WillAyd/orgs',
  'repos_url': 'https://api.github.com/users/WillAyd/repos',
  'events_url': 'https://api.github.com/users/WillAyd/events{/privacy}',
  'received_events_url': 'https://api.github.com/users/WillAyd/received_events',
  'type': 'User',
  'site_admin': False},
 'labels': [{'id': 48070600,
   'node_id': 'MDU6TGFiZWw0ODA3MDYwMA==',
   'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/CI',
   'name': 'CI',
   'color': 'a2bca7',
   'default': False,
   'description': 'Continuous Integration'}],
 'state': 'open',
 'locked': False,
 'assignee': None,
 'assignees': [],
 'milestone': None,
 'comments': 0,
 'created_at': '2022-03-30T05:31:11Z',
 'updated_at': '2022-03-30T05:31:18Z',
 'closed_at': None,
 'author_association': 'MEMBER',
 'active_lock_reason': None,
 'draft': True,
 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46570',
  'html_url': 'https://github.com/pandas-dev/pandas/pull/46570',
  'diff_url': 'https://github.com/pandas-dev/pandas/pull/46570.diff',
  'patch_url': 'https://github.com/pandas-dev/pandas/pull/46570.patch',
  'merged_at': None},
 'body': '- [X] closes #46532 \r\n\r\nPOC using docker compose, which is also used by the arrow project. \r\n\r\nThe idea here is that we can simply run `docker compose build db-testing` to build an image with postgres (can later add mysql) and our minimal development requirements then `docker compose run --rm db-testing` to run relevant tests. This can be done both by a developer as well as on GH actions.\r\n\r\nThis still needs a bit more work as it currently muddles user permissions on the host when building pandas\r\n\r\ncc @jonashaag who looks to have been doing some awesome work on CI lately',
 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/reactions',
  'total_count': 0,
  '+1': 0,
  '-1': 0,
  'laugh': 0,
  'hooray': 0,
  'confused': 0,
  'heart': 0,
  'rocket': 0,
  'eyes': 0},
 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46570/timeline',
 'performed_via_github_app': None}

In [20]:
data1[0]['user']['id'] #printing id at 0 index

609873

In [25]:
for i in range(len(data1)):
    print(data1[i]['user']['id']) #printing all id

609873
89279983
8078968
10647082
5728311
13159005
175722
33491632
66919765
33491632
45562402
291575
291575
4476168
15173842
72529861
30088608
24256554
41546976
45976948
45976948
6355796
175722
26720860
609873
22035922
45562402
36619387
26720860
4476168

### obtaining urls

In [35]:
df2= pd.DataFrame(data1,columns=['url','repository_url','labels_url','user'])
df2

,url,repository_url,labels_url,user
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'WillAyd', 'id': 609873, 'node_id': ..."
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'kevinhodes', 'id': 89279983, 'node_..."
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'jbrockmendel', 'id': 8078968, 'node..."
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'mroeschke', 'id': 10647082, 'node_i..."
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'ian-r-rose', 'id': 5728311, 'node_i..."
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'simonjayhawkins', 'id': 13159005, '..."
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'jonashaag', 'id': 175722, 'node_id'..."
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'MarcoGorelli', 'id': 33491632, 'nod..."
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'Kyrpel', 'id': 66919765, 'node_id':..."
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'MarcoGorelli', 'id': 33491632, 'nod..."
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'rhshadrach', 'id': 45562402, 'node_..."
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'flying-sheep', 'id': 291575, 'node_..."
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'flying-sheep', 'id': 291575, 'node_..."
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'kwhkim', 'id': 4476168, 'node_id': ..."
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'carlosan1708', 'id': 15173842, 'nod..."
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'bikoboshi', 'id': 72529861, 'node_i..."
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'kwsp', 'id': 30088608, 'node_id': '..."
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'attack68', 'id': 24256554, 'node_id..."
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'GYHHAHA', 'id': 41546976, 'node_id'..."
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'anmyachev', 'id': 45976948, 'node_i..."
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'anmyachev', 'id': 45976948, 'node_i..."
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'davehemming', 'id': 6355796, 'node_..."
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'jonashaag', 'id': 175722, 'node_id'..."
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'FactorizeD', 'id': 26720860, 'node_..."
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'WillAyd', 'id': 609873, 'node_id': ..."
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'furechan', 'id': 22035922, 'node_id..."
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'rhshadrach', 'id': 45562402, 'node_..."
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'weikhor', 'id': 36619387, 'node_id'..."
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'FactorizeD', 'id': 26720860, 'node_..."
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,"{'login': 'kwhkim', 'id': 4476168, 'node_id': ..."

In [40]:
df2.to_csv('json_res.csv',index = False)

In [41]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 8A66-F804

 Directory of C:\Users\Rokaya Neeraj\Full Stack Data Science\Python\Da13-Pandas

03/30/2022  01:19 PM    <DIR>          .
03/30/2022  01:19 PM    <DIR>          ..
03/28/2022  01:41 PM    <DIR>          .ipynb_checkpoints
03/29/2022  12:37 PM             5,658 criket.csv
03/30/2022  01:19 PM            34,268 json_res.csv
03/28/2022  02:27 PM           161,651 LUSID Excel - Business Agility - Making Simple Changes Quickly & Easily.xlsx
03/28/2022  02:27 PM           161,410 LUSID Excel - Maintain a product in multiple currencies and share classes.xlsx
03/28/2022  02:27 PM            24,471 LUSID Excel - Manage instruments with economic definitions.xlsx
03/28/2022  02:27 PM            84,319 LUSID Excel - Manage Orders.xlsx
03/28/2022  02:27 PM           137,753 LUSID Excel - Manage your investment strategies.xlsx
03/28/2022  02:27 PM           184,013 LUSID Excel - Setting up your IBOR.xlsx
03/28/2022  02:27 PM           136,632 LUSID Excel - Setting up your market data.xlsx
03/29/2022  12:08 PM            81,551 NBA.csv
03/29/2022  12:24 PM            78,960 NBA2.csv
03/30/2022  01:19 PM           446,259 Pandas(only structured datas).ipynb
              12 File(s)      1,536,945 bytes
               3 Dir(s)  20,626,300,928 bytes free

### from the above created json, make new columns for the user by the respective title heads present in the user column

In [84]:
import pandas
import requests
url = "https://api.github.com/repos/pandas-dev/pandas/issues"

In [85]:
data = requests.get(url)
data

In [86]:
data1 = data.json()
data1

[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46582',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46582/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46582/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46582/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/46582',
  'id': 1187859377,
  'node_id': 'I_kwDOAA0YD85GzUux',
  'number': 46582,
  'title': 'BUG: pandas cannot recognize date objects as datetime like values',
  'user': {'login': 'dcsaba89',
   'id': 54766615,
   'node_id': 'MDQ6VXNlcjU0NzY2NjE1',
   'avatar_url': 'https://avatars.githubusercontent.com/u/54766615?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/dcsaba89',
   'html_url': 'https://github.com/dcsaba89',
   'followers_url': 'https://api.github.com/users/dcsaba89/followers',
   'following_url': 'https://api.github.com/users/dcsaba89/following{/other_user}',
   'gists_url': 'https://api.github.com/users/dcsaba89/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/dcsaba89/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/dcsaba89/subscriptions',
   'organizations_url': 'https://api.github.com/users/dcsaba89/orgs',
   'repos_url': 'https://api.github.com/users/dcsaba89/repos',
   'events_url': 'https://api.github.com/users/dcsaba89/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/dcsaba89/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-03-31T10:20:43Z',
  'updated_at': '2022-03-31T10:20:43Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,
  'body': "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport datetime as dt\r\nimport pandas as pd\r\n\r\nd1 = dt.datetime(2020, 10, 10)\r\nyear1 = d1.year  # This works, year1 == 2020\r\n\r\nd2 = dt.date(2020, 10, 10)\r\nyear2 = d2.year  # This works, year2 == 2020\r\n\r\ndf = pd.DataFrame({'DATE_STR': ['2020-10-10']})\r\ndf['DATETIME'] = pd.to_datetime(df['DATE_STR'])\r\ndf['DATE'] = df['DATETIME'].dt.date\r\n\r\n\r\nprint(df.to_string(index=False))\r\n\r\nyearA = df['DATETIME'].dt.year # This works\r\nyearB = df['DATE'].dt.year  # AttributeError: Can only use .dt accessor with datetimelike values. Did you mean: 'at'?\n```\n\n\n### Issue Description\n\nPandas cannot recognize datetime.date(...) objects as datetime like values.\r\n\r\npandas.Series.dt.year, pandas.Series.dt.month, pandas.Series.dt.day, etc ... does not work with dt.date(...) objects.\n\n### Expected Behavior\n\ndf['DATETIME'].dt.year and df['DATE'].dt.year must be identical if df['DATETIME'] and df['DATE'] contains the same dates as datetime and date objects respectively.\r\n\r\nIn general, all pd.Series.dt methods like day, month, year, etc that replicates datetime methods for pd.Series should return the same output as the underlying datetime methd.\r\n\r\nFor example if dt.datetime(2020, 10, 10).month and dt.date(2020, 10, 10).month both return 10, then pd.Series([dt.datetime(2020, 10, 10)]).dt.month and pd.Series([dt.date(2020, 10, 10)]).dt.month should be identical and should return the same value ( = 10) as the underlying datetime methods.\n\n### Installed Versions\n\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5\r\npython           : 3.9.7.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.22000\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 142 Stepping 12, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : English_United States.1252\r\n\r\npandas           : 1.3.4\r\nnumpy            : 1.20.3\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 21.2.4\r\nsetuptools       : 58.0.4\r\nCython           : 0.29.24\r\npytest           : 6.2.4\r\nhypothesis       : None\r\nsphinx           : 4.2.0\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 3.0.1\r\nlxml.etree       : 4.6.3\r\nhtml5lib         : 1.1\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 2.11.3\r\nIPython          : 7.29.0\r\npandas_datareader: None\r\nbs4              : 4.10.0\r\nbottleneck       : 1.3.2\r\nfsspec           : 2021.10.1\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : 3.4.3\r\nnumexpr          : 2.7.3\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.7.1\r\nsqlalchemy       : 1.4.22\r\ntables           : 3.6.1\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 2.0.1\r\nxlwt             : 1.3.0\r\nnumba            : 0.54.1",
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46582/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46582/timeline',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46581',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46581/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46581/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46581/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/46581',
  'id': 1187766119,
  'node_id': 'I_kwDOAA0YD85Gy99n',
  'number': 46581,
  'title': 'BUG: Possible bug with `Series.agg()`',
  'user': {'login': 'kwhkim',
   'id': 4476168,
   'node_id': 'MDQ6VXNlcjQ0NzYxNjg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/4476168?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/kwhkim',
   'html_url': 'https://github.com/kwhkim',
   'followers_url': 'https://api.github.com/users/kwhkim/followers',
   'following_url': 'https://api.github.com/users/kwhkim/following{/other_user}',
   'gists_url': 'https://api.github.com/users/kwhkim/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/kwhkim/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/kwhkim/subscriptions',
   'organizations_url': 'https://api.github.com/users/kwhkim/orgs',
   'repos_url': 'https://api.github.com/users/kwhkim/repos',
   'events_url': 'https://api.github.com/users/kwhkim/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/kwhkim/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-03-31T09:18:02Z',
  'updated_at': '2022-03-31T09:28:26Z',
  'closed_at': None,
  'author_association': 'CONTRIBUTOR',
  'active_lock_reason': None,
  'body': '### Pandas version checks\r\n\r\n- [X] I have checked that this issue has not already been reported.\r\n\r\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\r\n\r\n- [X] I have confirmed this bug exists on the main branch of pandas.\r\n\r\n\r\nI must admit there were similar complaints before, here I present my analysis and solution.\r\n\r\n### Reproducible Example\r\n\r\n```python\r\nimport pandas as pd\r\nimport numpy as np\r\ndat = pd.DataFrame({\'color\':[\'A\', \'A\', \'E\', \'E\', \'J\'],\r\n                    \'carat\':[0.23, 0.21, 0.23, 0.29, 0.31],\r\n                    \'x\':[3.95, 3.89, 4.05, 4.20, 4.34]},\r\n                  index = [1,2,3,4,5])\r\n\r\ndat[\'carat\'].agg(np.mean)\r\n## 0.254\r\ndat[\'carat\'].agg(np.mean, axis=0)\r\n## 0.254\r\ndat[\'carat\'].agg(\'mean\')\r\n## 0.254\r\ndat[\'carat\'].agg(lambda x: np.mean(x))\r\n## 1    0.23\r\n## 2    0.21\r\n## 3    0.23\r\n## 4    0.29\r\n## 5    0.31\r\n## Name: carat, dtype: float64\r\ndat[\'carat\'].agg(lambda x, axis: np.mean(x, axis=axis), axis=0)\r\n## TypeError: <lambda>() missing 1 required positional argument: \'axis\'\r\n\r\n\r\nCompare the result above with the result below\r\n\r\n```python\r\ndat[\'carat\'].groupby(dat[\'color\']).agg(np.mean), \r\ndat[\'carat\'].groupby(dat[\'color\']).agg(np.mean, axis=0), \r\ndat[\'carat\'].groupby(dat[\'color\']).agg(\'mean\'), \r\ndat[\'carat\'].groupby(dat[\'color\']).agg(lambda x: np.mean(x)), \r\ndat[\'carat\'].groupby(dat[\'color\']).agg(lambda x, axis: np.mean(x, axis=axis), axis=0)\r\n## <all the same here>\r\n## color\r\n## A    0.22\r\n## E    0.26\r\n## J    0.31\r\n## Name: carat, dtype: float64,\r\n##\r\n##\r\n```\r\n\r\nCall it bug or inconsistency or poor design?\r\n\r\n\r\n### Issue Description\r\n\r\nBasically, in consistency\'s term,  `pd.Series.agg()` and `pd.Series.groupby().agg()` should act the same way.\r\n\r\nAnyway as I read the the code(the code is in the bottom), I found parameter axis for `Series.aggregate()` seems useless(or am I missing something here?)\r\n\r\nEven if it really needs a named paramter, it\'d better be named something like `_axis_` to avoid conflicting names with \r\nfunctions to apply. For example `np.mean()` has a parameter named `axis=` and user might name a parameter `axis` (for example, `lambda x, axis: np.mean(x, axis=axis)`). \r\n\r\nAs far as I know, we do not need `axis=0` and ` self._get_axis_number(axis)` for Series at least(DataFrame has similar signature, and I think it should be renamed to something like `_axis_` or `_axis` or `__axis__`).\r\n\r\nSo I propose deleting `axis` parameter from Series.aggregate and renaming `axis` to `_axis` for DataFrame.aggreate.\r\n\r\n```\r\n    def aggregate(self, func=None, axis=0, *args, **kwargs):\r\n        # Validate the axis parameter\r\n        self._get_axis_number(axis)\r\n\r\n        # if func is None, will switch to user-provided "named aggregation" kwargs\r\n        if func is None:\r\n            func = dict(kwargs.items())\r\n\r\n        op = SeriesApply(self, func, convert_dtype=False, args=args, kwargs=kwargs)\r\n        result = op.agg()\r\n        return result\r\n```\r\n\r\n### Expected Behavior\r\n\r\n`dat[\'carat\'].groupby(dat[\'color\']).agg(lambda x: np.mean(x))` and\r\n`dat[\'carat\']..agg(lambda x: np.mean(x))` works similarly\r\n\r\n### Installed Versions\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 06d230151e6f18fdb8139d09abf539867a8cd481\r\npython           : 3.8.12.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19044\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : Korean_Korea.949\r\n\r\npandas           : 1.4.1\r\nnumpy            : 1.22.2\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 22.0.3\r\nsetuptools       : 60.9.3\r\nCython           : 0.29.28\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : 4.8.0\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.0.1\r\npandas_datareader: None\r\nbs4              : 4.10.0\r\nbottleneck       : None\r\nfastparquet      : None\r\nfsspec           : 2022.02.0\r\ngcsfs            : None\r\nmatplotlib       : 3.5.1\r\nnumba            : None\r\nnumexpr          : 2.8.1\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : 1.0.9\r\ns3fs             : None\r\nscipy            : 1.8.0\r\nsqlalchemy       : None\r\ntables           : 3.7.0\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : 2.0.1\r\nxlwt             : None\r\nzstandard        : None\r\n',
  'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46581/reactions',
   'total_count': 0,
   '+1': 0,
   '-1': 0,
   'laugh': 0,
   'hooray': 0,
   'confused': 0,
   'heart': 0,
   'rocket': 0,
   'eyes': 0},
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46581/timeline',
  'performed_via_github_app': None},
 {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46580',
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46580/labels{/name}',
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46580/comments',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46580/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/46580',
  'id': 1187761681,
  'node_id': 'I_kwDOAA0YD85Gy84R',
  'number': 46580,
  'title': 'BUG: Reading a subset of columns with read_fwf fails if names are given when widths argument is used',
  'user': {'login': 'xnx',
   'id': 371774,
   'node_id': 'MDQ6VXNlcjM3MTc3NA==',
   'avatar_url': 'https://avatars.githubusercontent.com/u/371774?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/xnx',
   'html_url': 'https://github.com/xnx',
   'followers_url': 'https://api.github.com/users/xnx/followers',
   'following_url': 'https://api.github.com/users/xnx/following{/other_user}',
   'gists_url': 'https://api.github.com/users/xnx/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/xnx/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/xnx/subscriptions',
   'organizations_url': 'https://api.github.com/users/xnx/orgs',
   'repos_url': 'https://api.github.com/users/xnx/repos',
   'events_url': 'https://api.github.com/users/xnx/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/xnx/received_events',
   'type': 'User',
   'site_admin': False},
  'labels': [{'id': 76811,
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug',
    'name': 'Bug',
    'color': 'e10c02',
    'default': False,
    'description': None},
   {'id': 1954720290,
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage',
    'name': 'Needs Triage',
    'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member'}],
  'state': 'open',
  'locked': False,
  'assignee': None,
  'assignees': [],
  'milestone': None,
  'comments': 0,
  'created_at': '2022-03-31T09:15:13Z',
  'updated_at': '2022-03-31T09:15:13Z',
  'closed_at': None,
  'author_association': 'NONE',
  'active_lock_reason': None,

In [87]:
df = pd.DataFrame(data1)
df.head()

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,updated_at,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46582,1187859377,I_kwDOAA0YD85GzUux,46582,BUG: pandas cannot recognize date objects as d...,...,2022-03-31T10:20:43Z,None,NONE,None,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46581,1187766119,I_kwDOAA0YD85Gy99n,46581,BUG: Possible bug with `Series.agg()`,...,2022-03-31T09:28:26Z,None,CONTRIBUTOR,None,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46580,1187761681,I_kwDOAA0YD85Gy84R,46580,BUG: Reading a subset of columns with read_fwf...,...,2022-03-31T09:15:13Z,None,NONE,None,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/46579,1187594420,I_kwDOAA0YD85GyUC0,46579,BUG: inconsistent behavior of `pd.Series.astyp...,...,2022-03-31T07:45:48Z,None,NONE,None,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/46578,1187436344,PR_kwDOAA0YD841XXPt,46578,REF: expose pandas_timedelta_to_timedeltastruct,...,2022-03-31T03:53:09Z,None,MEMBER,None,Broken off from a branch implementing non-nano...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,False,{'url': 'https://api.github.com/repos/pandas-d...

### DAY ---    3

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Understanding data

In [4]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [8]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

### Describing object columns

In [11]:
df.dtypes == "object"

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [12]:
type(df.dtypes)

pandas.core.series.Series

In [17]:
df.dtypes[df.dtypes == 'object']#means, show all the dataype of object where datatype is object

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [18]:
df.dtypes[df.dtypes == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [19]:
col_name = df.dtypes[df.dtypes == 'object'].index

In [20]:
col_name

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [22]:
df[col_name]

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [23]:
df[col_name].describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [24]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

### Adding new column

In [25]:
df['ineuron'] = "sudh"

In [26]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ineuron
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,sudh
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,sudh
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,sudh
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,sudh
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,sudh
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,sudh
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,sudh
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,sudh
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,sudh
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,sudh

In [29]:
df[['Name','Ticket']] #selecting columns

                                                  Name            Ticket
0                              Braund, Mr. Owen Harris         A/5 21171
1    Cumings, Mrs. John Bradley (Florence Briggs Th...          PC 17599
2                               Heikkinen, Miss. Laina  STON/O2. 3101282
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)            113803
4                             Allen, Mr. William Henry            373450
..                                                 ...               ...
886                              Montvila, Rev. Juozas            211536
887                       Graham, Miss. Margaret Edith            112053
888           Johnston, Miss. Catherine Helen "Carrie"        W./C. 6607
889                              Behr, Mr. Karl Howell            111369
890                                Dooley, Mr. Patrick            370376

[891 rows x 2 columns]

In [30]:
df['Name'][0:15] #slicing

0                               Braund, Mr. Owen Harris
1     Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                Heikkinen, Miss. Laina
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                              Allen, Mr. William Henry
5                                      Moran, Mr. James
6                               McCarthy, Mr. Timothy J
7                        Palsson, Master. Gosta Leonard
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                   Nasser, Mrs. Nicholas (Adele Achem)
10                      Sandstrom, Miss. Marguerite Rut
11                             Bonnell, Miss. Elizabeth
12                       Saundercock, Mr. William Henry
13                          Andersson, Mr. Anders Johan
14                 Vestrom, Miss. Hulda Amanda Adolfina
Name: Name, dtype: object

In [31]:
df['Name'][0:15:2]

0                               Braund, Mr. Owen Harris
2                                Heikkinen, Miss. Laina
4                              Allen, Mr. William Henry
6                               McCarthy, Mr. Timothy J
8     Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
10                      Sandstrom, Miss. Marguerite Rut
12                       Saundercock, Mr. William Henry
14                 Vestrom, Miss. Hulda Amanda Adolfina
Name: Name, dtype: object

In [38]:
df[df['Age'].isnull() == True]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ineuron
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,sudh
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,sudh
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,sudh
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,sudh
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,sudh
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,sudh
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,sudh
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,sudh
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,sudh
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,sudh

In [42]:
ind = df[df['Age'].isnull() == True].index

In [44]:
len(ind)

177

In [47]:
df.loc[ind]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ineuron
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,sudh
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,sudh
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,sudh
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,sudh
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,sudh
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,sudh
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,sudh
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,sudh
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,sudh
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,sudh

In [48]:
#OR
df[df['Age'].isnull() == True]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,ineuron
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q,sudh
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S,sudh
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C,sudh
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C,sudh
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q,sudh
...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C,sudh
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S,sudh
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S,sudh
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S,sudh
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,sudh

In [64]:
max(df['Fare'])

512.3292

In [63]:
df[df['Fare'] == max(df['Fare'])]['Name']

258                      Ward, Miss. Anna
679    Cardeza, Mr. Thomas Drake Martinez
737                Lesurer, Mr. Gustave J
Name: Name, dtype: object

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

### Number of male passanger

In [76]:
z = df[df['Sex'] == 'male']
male_count = len(z)
print(male_count)
#ans - 577 male passanger

577

In [2]:
#'OR'
df['Sex'].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [4]:
# 'OR'
df.groupby('Sex')['Sex'].count()

Sex
female    314
male      577
Name: Sex, dtype: int64

### Number of female passanger

In [59]:
y = df[df['Sex'] == 'female']
female_count = len(y)
print(female_count)
#ans - 314 female passanger

314

### how many survived?

In [60]:
x = df[df['Survived'] == 1]
survived_count = len(x)
print(survived_count)
#Ans - 342 survived

342

In [7]:
#'OR'
df['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [12]:
#'OR'
df.groupby('Survived')['Survived'].count()

Survived
0    549
1    342
Name: Survived, dtype: int64

### how many casualty?

In [62]:
x = df[df['Survived'] == 0]
casualty_count = len(x)
print(casualty_count)
#Ans  - 549 casualty

549

### what is a name of a person who is the eldest one?

In [73]:
max(df['Age'])

80.0

In [13]:
df[df['Age'] == max(df['Age'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

In [71]:
df[df['Age'] == max(df['Age'])]['Name']
#ans - Barkworth, Mr. Algernon Henry Wilson

630    Barkworth, Mr. Algernon Henry Wilson
Name: Name, dtype: object

### 4. how many passanger do we have in 1,2,3 class

In [81]:
passager_firstclass= df[df['Pclass'] == 1]
print(len(passager_firstclass))
### 216 passanger in 1st class

216

In [15]:
'OR'
df['Pclass'].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [16]:
'OR'
df.groupby('Pclass')['Pclass'].count()

Pclass
1    216
2    184
3    491
Name: Pclass, dtype: int64

In [82]:
passager_secondclass= df[df['Pclass'] == 2]
print(len(passager_secondclass))
### 184 passanger in 2nd class

184

In [83]:
passager_thirdclass= df[df['Pclass'] == 3]
print(len(passager_thirdclass))
### 491 passanger in 3rd class

491

### 5. how many person do we have who name starts with 's'

In [19]:
sname = df[df.Name.str.startswith("S")]['Name']
len(sname)
### 86 peoples name start with s

86

### 6. try to create a new column which is the summation of 'sibsp' and 'parch'

In [97]:
df['New Column'] = df['SibSp'] + df['Parch']
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,New Column
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0

### 7. how many person below age 25

In [20]:
lessthan_twentyfive = df[df['Age'] < 25 ]['Age']
len(lessthan_twentyfive )
### 278 peoples have age below 25

278

### 8. how many person died whose age was less than 40

In [26]:
result = df[(df['Survived']) == 0 & (df['Age'] < 40)] 
len(result)
#549 person died whose age was less than 40

549

### 9. from a cabin column separate text and numeric

In [37]:
import re
df1 = df
replace = re.compile("([a-zA-Z]+)")

df1['Cabin_numbers'] = df1['Cabin'].str.extract(replace)
df1['Cabin_characters'] = df1['Cabin'].str.replace(replace,"")
df1.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,numbers,characters,Cabin_numbers,Cabin_characters
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,NaN,NaN,NaN,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C,85,C,85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,NaN,NaN,NaN,NaN

### ----Questions from bank.csv

In [55]:
import pandas as pd
df = pd.read_csv('Bank.csv',delimiter = ';')
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

### 1. How many campaign available in this dataset

In [13]:
len(df['campaign'].unique())
#32 campaign

32

In [14]:
#"OR"
len(set(df['campaign'])) #first select campaign column.Then converted it to set because set gives us unique element.Now, if we 
# print the length of it, it will give us the number of campaign.

32

### 2. How many users do we have with housing and personal loan

In [15]:
h_p_loan = df[(df['housing'] == 'yes') & (df['loan'] == 'yes')]
print(len(h_p_loan))
# 406 users have both housing and personal loan.

406

### 3. How many person do we have whose age is 60+.

In [16]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [17]:
sixty_plus = df[df['age'] > 60]
print(len(sixty_plus))
#127 person has age above 60.

127

### 4. In which month we have targeted most of the customer

In [18]:
df2 = df.groupby('month')['month'].count()
print(df2)
#from the result, we can see that, we have targeted most of the customer in  may.

month
apr     293
aug     633
dec      20
feb     222
jan     148
jul     706
jun     531
mar      49
may    1398
nov     389
oct      80
sep      52
Name: month, dtype: int64

In [28]:
df['month'].value_counts().sort_values(ascending = False)

may    1398
jul     706
aug     633
jun     531
nov     389
apr     293
feb     222
jan     148
oct      80
sep      52
mar      49
dec      20
Name: month, dtype: int64

### 5. Which mode of call is giving you a more result.

In [41]:
df2 = df
df2 = df2.groupby(['contact','y']).count()
df2

                age   job  marital  education  default  balance  housing  \
contact   y
cellular  no   2480  2480     2480       2480     2480     2480     2480
          yes   416   416      416        416      416      416      416
telephone no    257   257      257        257      257      257      257
          yes    44    44       44         44       44       44       44
unknown   no   1263  1263     1263       1263     1263     1263     1263
          yes    61    61       61         61       61       61       61

               loan   day  month  duration  campaign  pdays  previous  \
contact   y
cellular  no   2480  2480   2480      2480      2480   2480      2480
          yes   416   416    416       416       416    416       416
telephone no    257   257    257       257       257    257       257
          yes    44    44     44        44        44     44        44
unknown   no   1263  1263   1263      1263      1263   1263      1263
          yes    61    61     61        61        61     61        61

               poutcome
contact   y
cellular  no       2480
          yes       416
telephone no        257
          yes        44
unknown   no       1263
          yes        61

In [44]:
df2.loc['cellular','yes'][0]

416

In [45]:
max(df2.loc['cellular','yes'][0],df2.loc['telephone','yes'][0],df2.loc['unknown','yes'][0])

416

In [ ]:
# we can conclued that cellular mode of call gives more result.

### 6. How many entrpreneurs do we have in this list.

In [ ]:
count_entrepreneur = df[df['job'] == 'entrepreneur']
print(len(count_entrepreneur))
#168 peoples in the data are entrepreneur.

### 7. How many customers do we have with negative balance.

In [46]:
df.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [51]:
len(df[df['balance'] < 0])

366

### 8. Prepare a group of data based on education level.

In [59]:
l=[]
for  i in df['education'].unique():
    l.append(df[df['education'] == i])

In [61]:
l[0].head(2)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
9,43,services,married,primary,no,-88,yes,yes,cellular,17,apr,313,1,147,2,failure,no

In [62]:
l[1].head(2)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no

In [63]:
l[2].head(2)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no

In [64]:
l[3].head(2)

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
20,38,management,divorced,unknown,no,0,yes,no,cellular,18,nov,96,2,-1,0,unknown,no
27,67,retired,married,unknown,no,696,no,no,telephone,17,aug,119,1,105,2,failure,no

### task

read all the resume from ineuron git in pdf,word and try to create a dataframe with resume name as a index value, and 

in column, i am expecting email id, linkedin id. git id , skills. Use regular expression

###  DAY - 4

In [69]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [68]:
df.dropna().head(2) #dropping row where NAN values
#axis = 0 means rows and axis = 1 means column
#no changes in original dataframe.If we have to change the dataframe permanently, we can do,df.dropna(inplace = True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S

In [72]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [75]:
df.dropna(axis = 1,thresh =800) #thresh means there should be that many number of non nan values for not dropping
#press shift tab after df.dropna so that we can get definition of everything possible that we can enter

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500,Q

In [85]:
df['Age']= df['Age'].fillna(value = df['Age'].mean()) #filling age column nan value with average of age
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [91]:
df.groupby('Survived').describe()['PassengerId'].transpose() #transpose chanes row to column and viceversa

Survived           0           1
count     549.000000  342.000000
mean      447.016393  444.368421
std       260.640469  252.358840
min         1.000000    2.000000
25%       211.000000  250.750000
50%       455.000000  439.500000
75%       675.000000  651.500000
max       891.000000  890.000000

In [96]:
df1 = pd.read_csv('Bank.csv', sep = ";")
df1.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no